const data = {
  assets: [
    {
      _id: '1',
      gps: 'GT-353-4281',
      owner: 'Simon Skekpeh',
      image: '/houses/house1.jpg',
      map: '/houses/house1.jpg',
      bank: "GCB Circle Branch",
      status: 'Pending',
      beg_date: "01/02/2019",
      end_date: "01/02/2029",
      value: 350000,
      valuer: 'Bentsil and Co Associates',
      asset_type: 'House',
      bank_contact: "Kofi Amissah",
      bank_phone: "0244567656"
    },
    {
      _id: '2',
      gps: 'GT-353-5281',
      owner: 'John Amuah',
      image: '/houses/house2.jpg',
      map: '/houses/house1.jpg',
      bank: "Ecobank Ridge Branch",
      status: 'Pending',
      beg_date: "01/02/2019",
      end_date: "01/02/2029",
      value: 365000,
      valuer: 'Akufo Addo and Co Associates',
      asset_type: 'House',
      bank_contact: "Frank Nartey",
      bank_phone: "0247567656"
    },
    {
      _id: '3',
      gps: 'GT-353-4785',
      owner: 'Seth Terkpe',
      image: '/houses/house3.jpg',
      map: '/houses/house1.jpg',
      bank: "Chase Manhattan Bank",
      status: 'Completed',
      beg_date: "06/02/2019",
      end_date: "06/02/2029",
      value: 350000,
      valuer: 'Sam Arthur Ltd',
      asset_type: 'House',
      bank_contact: "Kofi Sam",
      bank_phone: "0244564432"
    },   
    {
      _id: '4',
      gps: 'GT-353-8381',
      owner: 'Kwaku Swanzy',
      image: '/houses/house4.jpg',
      map: '/houses/house4.jpg',
      bank: "GCB Circle Branch",
      status: 'Pending',
      beg_date: "01/02/2019",
      end_date: "01/02/2029",
      value: 350000,
      valuer: 'Bentsil and Co Associates',
      asset_type: 'House',
      bank_contact: "Kofi Amissah",
      bank_phone: "0244567656"
    },
    {
      _id: '5',
      gps: 'GT-373-4281',
      owner: 'louis Mensah',
      image: '/houses/house5.jpg',
      map: '/houses/house5.jpg',
      bank: "GCB Kaneshie Branch",
      status: 'Completed',
      beg_date: "01/02/2019",
      end_date: "01/02/2029",
      value: 350000,
      valuer: 'Bentsil and Co Associates',
      asset_type: 'House',
      bank_contact: "Kofi Amissah",
      bank_phone: "0244567656"
    },
    {
      _id: '6',
      gps: 'GT-373-6571',
      owner: 'John Sakwanah',
      image: '/houses/house6.jpg',
      map: '/houses/house6.jpg',
      bank: "Barclays Bank",
      status: 'Pending',
      beg_date: "01/02/2019",
      end_date: "01/02/2029",
      value: 350000,
      valuer: 'Bentsil and Co Associates',
      asset_type: 'House',
      bank_contact: "Kofi Menah",
      bank_phone: "0244567656"
    },
  ],
}
export default data
